//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by c:\usr\src\teraterm\source\teraterm\ttermpro.rc
//
#define IDI_TTERM                       100
#define IDR_ACC                         100
#define IDR_MENU                        100
#define IDI_VT                          101
#define IDI_TEK                         102
#define IDD_COMMENT_DIALOG              110
#define IDD_EXTERNAL_SETUP              111
#define IDR_TEKMENU                     1000
#define IDC_EDIT_COMMENT                1000
#define IDC_EDIT_FULLPATH               1001
#define IDC_FULLPATH_LABEL              1002
#define IDC_LINECOPY                    1003
#define IDC_MOUSE_CURSOR                1004
#define IDC_ALPHA_BLEND                 1008
#define IDC_CYGWIN_PATH                 1009
#define IDC_SELECT_FILE                 1010
#define IDC_DELIM_LIST                  1011
#define IDC_ANSI_COLOR                  1012
#define IDC_COLOR_RED                   1013
#define IDC_COLOR_GREEN                 1014
#define IDC_COLOR_BLUE                  1015
#define IDC_SAMPLE_COLOR                1016
#define IDD_PRNABORTDLG                 2100
#define IDD_FILETRANSDLG                2200
#define IDC_TRANSFNAME                  2201
#define IDC_TRANSBYTES                  2202
#define IDC_TRANSPAUSESTART             2203
#define IDC_TRANSHELP                   2299
#define IDD_PROTDLG                     2300
#define IDC_PROTOFNAME                  2301
#define IDC_PROTOPROT                   2302
#define IDC_PROTOPKTNUM                 2303
#define IDC_PROTOBYTECOUNT              2304
#define IDC_PROTOPERCENT                2305
#define ID_ACC_SENDBREAK                50001
#define ID_ACC_COPY                     50002
#define ID_ACC_NEWCONNECTION            50003
#define ID_ACC_PRINT                    50004
#define ID_ACC_EXIT                     50005
#define ID_ACC_PASTECR                  50006
#define ID_ACC_AREYOUTHERE              50007
#define ID_ACC_PASTE                    50008
#define ID_FILE_NEWCONNECTION           50110
#define ID_FILE_LOG                     50120
#define ID_FILE_SENDFILE                50130
#define ID_FILE_KERMITRCV               50141
#define ID_FILE_KERMITGET               50142
#define ID_FILE_KERMITSEND              50143
#define ID_FILE_KERMITFINISH            50144
#define ID_FILE_XRCV                    50145
#define ID_FILE_XSEND                   50146
#define ID_FILE_ZRCV                    50151
#define ID_FILE_ZSEND                   50152
#define ID_FILE_BPRCV                   50153
#define ID_FILE_BPSEND                  50154
#define ID_FILE_QVRCV                   50155
#define ID_FILE_QVSEND                  50156
#define ID_FILE_CHANGEDIR               50170
#define ID_FILE_PRINT2                  50180
#define ID_FILE_DISCONNECT              50190
#define ID_FILE_EXIT                    50199
#define ID_EDIT_COPY2                   50210
#define ID_EDIT_COPYTABLE               50220
#define ID_EDIT_PASTE2                  50230
#define ID_EDIT_PASTECR                 50240
#define ID_EDIT_CLEARSCREEN             50250
#define ID_EDIT_CLEARBUFFER             50260
#define ID_SETUP_TERMINAL               50310
#define ID_SETUP_WINDOW                 50320
#define ID_SETUP_FONT                   50330
#define ID_SETUP_KEYBOARD               50340
#define ID_SETUP_SERIALPORT             50350
#define ID_SETUP_TCPIP                  50360
#define ID_SETUP_GENERAL                50370
#define ID_SETUP_SAVE                   50380
#define ID_SETUP_RESTORE                50390
#define ID_SETUP_LOADKEYMAP             50395
#define ID_CONTROL_RESETTERMINAL        50410
#define ID_CONTROL_AREYOUTHERE          50420
#define ID_CONTROL_SENDBREAK            50430
#define ID_CONTROL_RESETPORT            50440
#define ID_CONTROL_OPENTEK              50450
#define ID_CONTROL_CLOSETEK             50460
#define ID_CONTROL_MACRO                50470
#define ID_HELP_INDEX2                  50910
#define ID_HELP_USING2                  50920
#define ID_HELP_ABOUT                   50990
#define ID_TEKFILE_PRINT                51110
#define ID_TEKFILE_EXIT                 51190
#define ID_TEKEDIT_COPY                 51210
#define ID_TEKEDIT_COPYSCREEN           51220
#define ID_TEKEDIT_PASTE                51230
#define ID_TEKEDIT_PASTECR              51240
#define ID_TEKEDIT_CLEARSCREEN          51250
#define ID_TEKSETUP_WINDOW              51310
#define ID_TEKSETUP_FONT                51320
#define ID_TEKVTWIN                     51410
#define ID_TEKHELP_INDEX                51910
#define ID_TEKHELP_USING                51920
#define ID_TEKHELP_ABOUT                51990
#define ID_EDIT_SELECTALL               52000
#define ID_FILE_CYGWINCONNECTION        52001
#define ID_FILE_COMMENTTOLOG            52004
#define ID_EDIT_EXTERNALSETUP           52005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        112
#define _APS_NEXT_COMMAND_VALUE         52006
#define _APS_NEXT_CONTROL_VALUE         1017
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
