//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ttpdlg.rc
//
#define IDD_TERMDLGJ                    100
#define IDI_TTERM                       100
#define IDC_TERMWIDTH                   101
#define IDC_TERMHEIGHT                  102
#define IDC_TERMISWIN                   103
#define IDC_TERMRESIZE                  104
#define IDC_TERMCRRCV                   105
#define IDC_TERMCRSEND                  106
#define IDC_TERMID                      107
#define IDC_TERMLOCALECHO               108
#define IDC_TERMANSBACKTEXT             109
#define IDC_TERMANSBACK                 110
#define IDC_TERMAUTOSWITCH              111
#define IDC_TERMKANJI                   112
#define IDC_TERMKANA                    113
#define IDC_TERMKANJISEND               114
#define IDC_TERMKANASEND                115
#define IDC_TERMKINTEXT                 116
#define IDC_TERMKIN                     117
#define IDC_TERMKOUTTEXT                118
#define IDC_TERMKOUT                    119
#define IDC_TERMRUSSHOST                120
#define IDC_TERMRUSSCLIENT              121
#define IDC_TERMHELP                    199
#define IDD_WINDLG                      200
#define IDC_WINTITLE                    201
#define IDC_WINBLOCK                    202
#define IDC_WINVERT                     203
#define IDC_WINHORZ                     204
#define IDC_WINHIDEMENU                 205
#define IDC_WINHIDETITLE                206
#define IDC_WINCOLOREMU                 207
#define IDC_WINSCROLL1                  208
#define IDC_WINSCROLL2                  209
#define IDC_WINSCROLL3                  210
#define IDC_WINTEXT                     211
#define IDC_WINBACK                     212
#define IDC_WINREV                      213
#define IDC_WINRED                      214
#define IDC_WINGREEN                    215
#define IDC_WINBLUE                     216
#define IDC_WINREDBAR                   217
#define IDC_WINGREENBAR                 218
#define IDC_WINBLUEBAR                  219
#define IDC_WINATTRTEXT                 220
#define IDC_WINATTR                     221
#define IDC_WINHELP                     299
#define IDD_KEYBDLG                     300
#define IDC_KEYBBS                      301
#define IDC_KEYBDEL                     302
#define IDC_KEYBMETA                    303
#define IDC_KEYBKEYBTEXT                304
#define IDC_KEYBKEYB                    305
#define IDC_KEYBHELP                    399
#define IDD_SERIALDLG                   400
#define IDC_SERIALPORT                  401
#define IDC_SERIALBAUD                  402
#define IDC_SERIALDATA                  403
#define IDC_SERIALPARITY                404
#define IDC_SERIALSTOP                  405
#define IDC_SERIALFLOW                  406
#define IDC_SERIALDELAYCHAR             407
#define IDC_SERIALDELAYLINE             408
#define IDC_SERIALHELP                  499
#define IDD_TCPIPDLG                    500
#define IDC_TCPIPHOST                   501
#define IDC_TCPIPADD                    502
#define IDC_TCPIPLIST                   503
#define IDC_TCPIPUP                     504
#define IDC_TCPIPREMOVE                 505
#define IDC_TCPIPDOWN                   506
#define IDC_TCPIPHISTORY                507
#define IDC_TCPIPAUTOCLOSE              508
#define IDC_TCPIPPORT                   509
#define IDC_TCPIPTELNET                 510
#define IDC_TCPIPTERMTYPELABEL          511
#define IDC_TCPIPTERMTYPE               512
#define IDC_TCPIPHELP                   599
#define IDD_HOSTDLG                     600
#define IDC_HOSTTCPIP                   601
#define IDC_HOSTSERIAL                  602
#define IDC_HOSTNAMELABEL               603
#define IDC_HOSTNAME                    604
#define IDC_HOSTTELNET                  605
#define IDC_HOSTTCPPORTLABEL            606
#define IDC_HOSTTCPPORT                 607
#define IDC_HOSTCOMLABEL                608
#define IDC_HOSTCOM                     609
#define IDC_HOSTHELP                    699
#define IDD_DIRDLG                      700
#define IDC_DIRCURRENT                  701
#define IDC_DIRNEW                      702
#define IDC_DIRHELP                     799
#define IDD_ABOUTDLG                    800
#define IDD_FONTDLG                     900
#define IDC_FONTBOLD                    901
#define IDC_FONTCHARSET1                902
#define IDC_FONTCHARSET2                903
#define IDD_GENDLG                      1000
#define IDC_GENPORT                     1001
#define IDC_GENLANGLABEL                1002
#define IDC_GENLANG                     1003
#define IDC_HOSTTCPPROTOCOLLABEL        1019
#define IDC_HOSTTCPPROTOCOL             1020
#define IDC_LOCALE_BOX                  1022
#define IDC_EDIT1                       1024
#define IDC_LOCALE_EDIT                 1024
#define IDC_CODEPAGE_LABEL              1025
#define IDC_EDIT2                       1026
#define IDC_CODEPAGE_EDIT               1026
#define IDC_TT_VERSION                  1027
#define IDC_AUTHOR_URL                  1028
#define IDC_FORUM_LABEL                 1029
#define IDC_FORUM_URL                   1030
#define IDC_ONIGURUMA_LABEL             1031
#define IDC_GENHELP                     1099
#define IDD_TERMDLG                     1100
#define IDD_WINLISTDLG                  1200
#define IDC_WINLISTLIST                 1201
#define IDC_WINLISTCLOSE                1202
#define IDC_WINLISTHELP                 1299
#define IDD_TERMDLGR                    1300
#define IDC_STATIC                      -1
#define IDC_LOCALE_LABEL                -1
#define IDC_AUTHOR_LABEL                -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1032
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
